
# Doctor Organization : This mainly involve creation of certificates for doctor nodes

# Initially 1 doctor is assumed now. it can be changed according to the requirements

PeerOrgs:

  - Name: DocOrg1
    Domain: docorg1.example2.com
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - localhost
      
    Users:
      Count: 1