# Hospital - Management Organization .

# Presently considering 4 peers as default

PeerOrgs:

  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true

    Template:
      Count: 4
      SANS:
        - localhost
      
    Users:
      Count: 1