# Orderer Nodes for the organization purpose

# The main task of this node is to provide ordering service for 
# the management blockchain that mainly stores the current set of active doctors in the hospital


OrdererOrgs:
  
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

