# Patient Organization : This mainly involve creation of certificates for Patient Nodes

# A single sample patient is created as of now . it will be updated based on the requirement.

PeerOrgs:

  - Name: PatOrg1
    Domain: patorg1.example3.com
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - localhost
      
    Users:
      Count: 1